GOALS:
1) Prove I can select files using file names and date range. 
1) Process 1 UIUC file
2) Process 1 USC file

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent.parent / "src"))

from config import load_config
from lidar.files import find_files_by_time

In [3]:
# test loading config 
paths = load_config('paths.yml')
usc_dir =  paths['paths']['usc_interim_dir']
uiuc_dir =  paths['paths']['uiuc_interim_dir']
lidar_dir = paths['paths']['lidar_dir']

print(lidar_dir)
print(uiuc_dir)
print(usc_dir)

C:/Users/ben/OneDrive - University of South Carolina/SAVANT_Data/01_interim
C:/Users/ben/OneDrive - University of South Carolina/SAVANT_Data/01_interim/UIUC
C:/Users/ben/OneDrive - University of South Carolina/SAVANT_Data/01_interim/USC

In [4]:

uiuc_files = find_files_by_time(
    root_dir=uiuc_dir+'/10152018',
    source="UIUC",
    start_time="2018-10-15 23:50:00",
    end_time="2018-10-16 00:10:00",
    pattern="R*",
    recursive=True,
)

uiuc_files.head()

,file_path,file_name,file_time,parse_error,selected
0,C:\Users\ben\OneDrive - University of South Ca...,R18A1523.490852.csv,2018-10-15 23:49:08.520,None,False
1,C:\Users\ben\OneDrive - University of South Ca...,R18A1523.491279.csv,2018-10-15 23:49:12.790,None,False
2,C:\Users\ben\OneDrive - University of South Ca...,R18A1523.491682.csv,2018-10-15 23:49:16.820,None,False
3,C:\Users\ben\OneDrive - University of South Ca...,R18A1523.492079.csv,2018-10-15 23:49:20.790,None,False
4,C:\Users\ben\OneDrive - University of South Ca...,R18A1523.492477.csv,2018-10-15 23:49:24.770,None,False

In [15]:
uiuc_files[uiuc_files['selected']==True].describe()

                        file_time
count                          51
mean   2018-10-16 00:01:53.078039
min    2018-10-16 00:00:14.910000
25%    2018-10-16 00:01:04.570000
50%    2018-10-16 00:01:53.630000
75%    2018-10-16 00:02:42.540000
max    2018-10-16 00:03:31.900000